@startuml command
class VueComponent as "UpdateItemCommand.vue" << (V, Orange) Vue component >> {
  store: Store
}

class Store {
  currentStudy: StudyAdapter,
  currentPatient: PatientAdapter,
  drivers: StudioDrivers,
  saveItems(items),
}

class StudyAdapter <<(C, HotPink) Proxy>> {
  name
  pages
  pageSets
  etc.
  start(command, ...args)
  getInterviewItems(pageSet)
  apply(interviewItems)
}

class InterviewStudioDriver {
  save(study, patient, interview)
}

class UpdateItemCommand {
}

class PatientAdapter <<(C, HotPink) Proxy>> {
  interviews
}

left to right direction
VueComponent .l.> UpdateItemCommand
VueComponent ..> StudyAdapter::start
VueComponent o-> Store
Store::saveItems ..> InterviewStudioDriver::save
Store::currentPatient ..> PatientAdapter::interviews
PatientAdapter::interviews ..> StudyAdapter::getInterviewItems
InterviewStudioDriver::save ..> StudyAdapter::apply
hide members
show Store members
show VueComponent fields
show StudyAdapter members
show InterviewStudioDriver methods
show PatientAdapter fields
@enduml
